csa/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # Send errors to root
  get '*path' => redirect('/')

end

csa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

csa/app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title

  belongs_to :user,optional: true
end

csa/app/models/user.rb
class User < ApplicationRecord
  has_many :posts,
           dependent: :destroy
end

csa/app/controllers/application_controller.rb
# Top-level class for common controller code
# @author Chris Loftus
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Make is_admin? a helper method available to view templates
  helper_method :is_admin?

  protected

  # Is the caller an admin user? Currently everyone is!
  # @return true if admin user else false
  def is_admin?
    true
  end
end

csa/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = User.find_by email: params[:email]

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

csa/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

csa/app/controllers/users_controller.rb
# Handles incoming user account HTTP requests
# @author Chris Loftus
# @modifier Nathan Hughes 
class UsersController < ApplicationController
  before_action :set_current_page, except: [:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page],
                           per_page: params[:per_page])
               .order('surname, forename')
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html {redirect_to(user_url(@user, page: @current_page),
                                 notice: 'Account was successfully created.')}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to(user_url(@user, page: @current_page),
                                 notice: 'Account was successfully updated.')}
        format.json {render :show, status: :ok, location: @user}
      else
        format.html {render :edit}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url(page: @current_page)}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def set_current_page
    @current_page = params[:page] || 1
  end

  # We inform the caller if the record no longer exists
  def show_record_not_found(exception)
    respond_to do |format|
      format.html {
        redirect_to(users_url(page: @current_page),
                    notice: 'Account no longer exists.')
      }
      format.json {
        render json: '{Account no longer exists.}',
               status: :unprocessable_entity
      }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:surname, :forename, :phone, :grad_year, :jobs, :email)
  end
end

csa/app/helpers/application_helper.rb
module ApplicationHelper
end

csa/app/helpers/posts_helper.rb
module PostsHelper
end

csa/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

csa/app/helpers/users_helper.rb
module UsersHelper
end

csa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Csa</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="header">
  <%= render :partial => 'sessions/login' %>
  <div class="navigation">
    <%= render_navigation %>
  </div>

  <% flash.each do |key, value| %>
    <span class="flash_<%= key %>">
      <span class="flash_message"><%= value %></span>
    </span>
  <% end %>

</div>
<div class="content">
  <%= yield %>
</div>

<div id="footer">
</div>

</body>
</html>

csa/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= if post.user
      text_field_tag 'email',post.user.email
    else
      text_field_tag 'email'
    end %>
  </div>
  
  <div class="field">
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

csa/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

csa/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <% if post.user %>
          <td> <%= link_to "#{post.user.email}", post.user %></td>
        <% else %>
           <td>Anonymous</td>
        <% end %>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

csa/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

csa/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Email:</strong>
  <% if @post.user %>
    <%= link_to "#{@post.user.email}", @post.user %>
  <% else %>
    Anonymous
  <% end %>
</p>

<p>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

csa/app/views/static_pages/home.html.erb
<h1>Welcome to the CSA webpage</h1>

<body>

<%= image_tag('monkey.gif', alt: 'Show', title: 'Show details', :style => "padding: 10px") %>
  
</body>

csa/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= hidden_field_tag 'page', @current_page %>

    <div class="field">
      <%= f.label :surname %><br>
      <%= f.text_field :surname %>
    </div>
    <div class="field">
      <%= f.label :forename %><br>
      <%= f.text_field :forename %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.phone_field :phone %>
    </div>
    <div class="field">
      <%= f.label :grad_year %><br>
      <%= f.number_field :grad_year %>
    </div>
    <div class="field">
      <%= f.label :jobs %><br>
      <%= f.check_box :jobs %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

csa/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', user_path(@user, page: @current_page) %> |
<%= link_to 'Back', users_path(page: @current_page) %>

csa/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Forename</th>
      <th>Phone</th>
      <th>Grad year</th>
      <th>Jobs</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.surname %></td>
        <td><%= user.forename %></td>
        <td><%= user.phone %></td>
        <td><%= user.grad_year %></td>
        <td><%= user.jobs %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

csa/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

csa/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Forename:</strong>
  <%= @user.forename %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Grad year:</strong>
  <%= @user.grad_year %>
</p>

<p>
  <strong>Jobs:</strong>
  <%= @user.jobs %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user, page: @current_page) %> |
<%= link_to 'Back', users_path(page: @current_page) %>